name: Hello World
author: Ishwar Raj Chauhan
description: Greet someone and record the time

inputs:
  who_to_greet:
    description: Who to greet
    required: true
    default: World

outputs:
  time:
    description: Time of greeting

runs:
  using: node20
  main: index.js