name: First Workflow
on: [push]       #trigger the workflow on push events only

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello, World!"
            - name: Multiline Commands
              run: |
                node -v
                npm -v

    parallel-job-macos:             #this job will run in parallel with the 'run-shell-commands' job
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers

    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands   #this job will only run after the successful completion of the 'run-shell-commands' job
        steps:
            - name: echo a string
              run: Write-Output "Window String"
            - name: Error Step
              run: doesnotexistsss
        